version: '3.8'
 
services:
  nginx:
    image: nginx:latest
    container_name: FE_Container_new
    ports:
      - "8000:80"
    volumes:
      - /home/Front_end_Code/Angular-Login/src:/usr/share/nginx/html 
    restart: always

