version: '3.8'
 
services:
  nginx:
    image: nginx:latest
    container_name: FE-Container3
    ports:
      - "8000:80"
    volumes:
      - /var/lib/jenkins/jobs/FE/workspace/Angular-Login/src:/usr/share/nginx/html 
    restart: always

